# Generated by Django 5.0.1 on 2024-02-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
